version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: garry2002/place:latest
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image:  mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test1
      # MYSQL_USER: example_user
      # MYSQL_PASSWORD: example_password
    ports:
      - "33062:3306"
    volumes:
      - ./mysql/test1.sql:/docker-entrypoint-initdb.d/init.sql #set init sql
      - db-data:/var/lib/mysql #on it's dir
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ''  #empty pwd of phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  db-data:
